site_name: FIWARE-Testbed-Deploy
site_url: https://fiware-testbed-deploy.readthedocs.org
repo_url: https://github.com/telefonicaid/fiware-testbed-deploy.git
site_description: FIWARE Murano Documentation
site_dir: html
docs_dir: doc
markdown_extensions: [toc, fenced_code]
use_directory_urls: false
theme: readthedocs
index_page: [index.md, README.md]
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
google_analytics: ['UA-82830081-1', 'fiware-testbed-deploy.readthedocs.io']
pages:
  - ['index.md', 'Welcome to FIWARE Testbed Deploy']
  - ['admin.md', 'FIWARE Testbed Deploy Admin Guide']
  - ['docker.md', 'Working with Docker']

