fiware-skuld-delete_testbed:
  image: fiware-skuld-delete_testbed
  environment: 
   - OS_AUTH_URL
   - OS_USERNAME
   - OS_TENANT_NAME
   - OS_PASSWORD
   - OS_REGION_NAME
   - OS_PROJECT_DOMAIN_NAME
   - OS_USER_DOMAIN_NAME

